Vagrant.configure("2") do |c|
  c.vm.box = "opscode-ubuntu-12.04"
  c.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box"
  c.vm.hostname = "default-ubuntu-1204.vagrantup.com"
  c.vm.network(:forwarded_port, {:guest=>8888, :host=>8888})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/chris.antenesse/repos/netcalc", "/netcalc", nil
  c.vm.provider :virtualbox do |p|
  end
end
